### ISSUE TITLE
How do we parse a file?

### ISSUE THREAD

**Issue by samprity** [joegesualdo/vtt-to-json#2]
Current example usage
```
const vttToJson = require("vtt-to-json") 
let vttString = "..."; 
vttToJson(vttString)
.then((result) => {
  console.log(result)
});
```
How can we load a webvtt file instead of using strings?

**Comment by joegesualdo** [comment]
It doesn't support file paths at the current time. Instead, you could get/read the file contents and then pass them to the function.
